/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/admin/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Login */
		post: operations["login_api_admin_login_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Logout */
		post: operations["logout_api_admin_logout_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Me */
		get: operations["me_api_admin_me_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/admins": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Listadmins */
		get: operations["listAdmins_api_admin_admins_get"];
		put?: never;
		/** Addadmin */
		post: operations["addAdmin_api_admin_admins_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/admins/{admin_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Deleteadmin */
		delete: operations["deleteAdmin_api_admin_admins__admin_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/uploads/presign": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Presignupload */
		post: operations["presignUpload_api_uploads_presign_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cases": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Listcases */
		get: operations["listCases_api_cases_get"];
		put?: never;
		/** Createcase */
		post: operations["createCase_api_cases_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cases/demo": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Getdemocase */
		get: operations["getDemoCase_api_cases_demo_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cases/{case_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Getcase */
		get: operations["getCase_api_cases__case_id__get"];
		/** Updatecase */
		put: operations["updateCase_api_cases__case_id__put"];
		post?: never;
		/** Deletecase */
		delete: operations["deleteCase_api_cases__case_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cases/{case_id}/version": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Getcaseversion */
		get: operations["getCaseVersion_api_cases__case_id__version_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/simulations/start": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Startsimulation */
		post: operations["startSimulation_api_simulations_start_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/simulations/{run_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Getsimulationstate */
		get: operations["getSimulationState_api_simulations__run_id__get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/simulations/{run_id}/export": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Exportsimulation */
		get: operations["exportSimulation_api_simulations__run_id__export_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/simulations/{run_id}/notes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Updatenotes */
		put: operations["updateNotes_api_simulations__run_id__notes_put"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/simulations/{run_id}/message": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sendmessage */
		post: operations["sendMessage_api_simulations__run_id__message_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** AddAdminRequest */
		AddAdminRequest: {
			/** Email */
			email: string;
			/** Name */
			name?: string | null;
			role: components["schemas"]["AdminRole"];
		};
		/** AdminDeletedResponse */
		AdminDeletedResponse: {
			/** Ok */
			ok: boolean;
			/** Cases Deleted */
			cases_deleted: number;
			/** Cases Reassigned */
			cases_reassigned: number;
		};
		/** AdminOut */
		AdminOut: {
			/** Id */
			id: number;
			/** Email */
			email: string;
			/** Name */
			name?: string | null;
			role: components["schemas"]["AdminRole"];
		};
		/**
		 * AdminRole
		 * @enum {integer}
		 */
		AdminRole: 1 | 2;
		/** CaseCreatedResponse */
		CaseCreatedResponse: {
			/** Case Id */
			case_id: number;
		};
		/** CaseDeletedResponse */
		CaseDeletedResponse: {
			/** Ok */
			ok: boolean;
		};
		/** CaseDetail */
		CaseDetail: {
			/** Id */
			id?: number | null;
			/** Case Name */
			case_name: string;
			/** Access Code */
			access_code?: string | null;
			/** Brief */
			brief: string;
			/** Common Information */
			common_information?: string | null;
			/** Simulation Duration */
			simulation_duration?: number | null;
			/** Personas */
			personas?: components["schemas"]["PersonaPayload"][];
			/** Referrals */
			referrals?: components["schemas"]["ReferralEdgePayload"][];
			/** Roots */
			roots?: string[];
			/** Version */
			version?: number | null;
			/** Owner Admin Id */
			owner_admin_id?: number | null;
			/** Collaborator Admin Ids */
			collaborator_admin_ids?: number[] | null;
		};
		/** CaseDetailResponse */
		CaseDetailResponse: {
			case: components["schemas"]["CaseDetail"];
		};
		/** CaseListResponse */
		CaseListResponse: {
			/** Cases */
			cases: components["schemas"]["CaseSummary"][];
		};
		/** CasePayload */
		CasePayload: {
			/** Case Name */
			case_name: string;
			/** Brief */
			brief: string;
			/** Common Information */
			common_information?: string | null;
			/** Simulation Duration */
			simulation_duration?: number | null;
			/** Access Code */
			access_code?: string | null;
			/** Personas */
			personas?: components["schemas"]["PersonaPayload"][];
			/** Referrals */
			referrals?: components["schemas"]["ReferralEdgePayload"][];
			/** Roots */
			roots?: string[];
			/** Collaborator Admin Ids */
			collaborator_admin_ids?: number[];
		};
		/** CaseSummary */
		CaseSummary: {
			/** Id */
			id: number;
			/** Case Name */
			case_name: string;
			/** Access Code */
			access_code?: string | null;
		};
		/** CaseUpdatePayload */
		CaseUpdatePayload: {
			/** Case Name */
			case_name: string;
			/** Brief */
			brief: string;
			/** Common Information */
			common_information?: string | null;
			/** Simulation Duration */
			simulation_duration?: number | null;
			/** Access Code */
			access_code?: string | null;
			/** Personas */
			personas?: components["schemas"]["PersonaPayload"][];
			/** Referrals */
			referrals?: components["schemas"]["ReferralEdgePayload"][];
			/** Roots */
			roots?: string[];
			/** Collaborator Admin Ids */
			collaborator_admin_ids?: number[];
			/** Expected Version */
			expected_version: number;
		};
		/** CaseVersionResponse */
		CaseVersionResponse: {
			/** Version */
			version: number;
		};
		/** ChatMessage */
		ChatMessage: {
			/**
			 * Role
			 * @enum {string}
			 */
			role: "user" | "assistant";
			/** Content */
			content: string;
		};
		/** ContactOut */
		ContactOut: {
			/** Id */
			id: string;
			/** Name */
			name: string;
			/** Role */
			role: string;
			profile_photo?: components["schemas"]["PersonaPhotoOut"] | null;
			/** Availability Duration */
			availability_duration?: number | null;
			/** Is Referred */
			is_referred: boolean;
			/** Available */
			available: boolean;
			/** Available In */
			available_in?: number | null;
			/** Expires In */
			expires_in?: number | null;
			/** Chat Ended */
			chat_ended: boolean;
			/** Chat End Reason */
			chat_end_reason?: string | null;
			/** Warning Count */
			warning_count: number;
		};
		/** ExportCaseSummary */
		ExportCaseSummary: {
			/** Id */
			id: number;
			/** Case Name */
			case_name: string;
		};
		/** ExportPersonaOut */
		ExportPersonaOut: {
			/** Id */
			id: string;
			/** Name */
			name: string;
			/** Role */
			role: string;
			/** Messages */
			messages: components["schemas"]["ChatMessage"][];
		};
		/** ExportResponse */
		ExportResponse: {
			case: components["schemas"]["ExportCaseSummary"];
			/** Personas */
			personas?: components["schemas"]["ExportPersonaOut"][];
		};
		/** FileEntry */
		FileEntry: {
			file?: components["schemas"]["FileRef"] | null;
			/** Share Conditions */
			share_conditions?: string | null;
			/** Perceived Contents */
			perceived_contents?: string | null;
		};
		/** FileRef */
		FileRef: {
			/** File Id */
			file_id?: string | null;
			/** Object Key */
			object_key: string;
			/** File Name */
			file_name: string;
			/** Content Type */
			content_type?: string | null;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/** LoginRequest */
		LoginRequest: {
			/** Credential */
			credential: string;
		};
		/** LoginResponse */
		LoginResponse: {
			/** Admin Id */
			admin_id: number;
			role: components["schemas"]["AdminRole"];
			/** Email */
			email: string;
			/** Name */
			name?: string | null;
		};
		/** NotesPayload */
		NotesPayload: {
			/** Notes */
			notes: string;
		};
		/** NotesResponse */
		NotesResponse: {
			/** Notes */
			notes: string;
		};
		/** PersonaPayload */
		PersonaPayload: {
			/** Id */
			id: string;
			/**
			 * Name
			 * @default
			 */
			name: string;
			/**
			 * Role
			 * @default
			 */
			role: string;
			profile_photo?: components["schemas"]["FileRef"] | null;
			/** Known Facts */
			known_facts?: string | null;
			/** Personality Traits */
			personality_traits?: string | null;
			/** Availability Minutes */
			availability_minutes?: number | null;
			/** Files */
			files?: components["schemas"]["FileEntry"][];
		};
		/** PersonaPhotoOut */
		PersonaPhotoOut: {
			/** File Id */
			file_id?: string | null;
			/** Object Key */
			object_key: string;
			/** File Name */
			file_name: string;
			/** Content Type */
			content_type?: string | null;
			/** Url */
			url: string;
		};
		/** PresignUploadRequest */
		PresignUploadRequest: {
			/** File Name */
			file_name: string;
			/** Content Type */
			content_type?: string | null;
			/** Prefix */
			prefix?: string | null;
		};
		/** PresignUploadResponse */
		PresignUploadResponse: {
			/** Upload Url */
			upload_url: string;
			/** Object Key */
			object_key: string;
			/** File Name */
			file_name: string;
			/** Content Type */
			content_type?: string | null;
			/** Expires In */
			expires_in: number;
		};
		/** ReferralEdgePayload */
		ReferralEdgePayload: {
			/** From Id */
			from_id: string;
			/** To Id */
			to_id: string;
			/** Conditions */
			conditions?: string | null;
		};
		/** RunCaseSummary */
		RunCaseSummary: {
			/** Id */
			id: number;
			/** Case Name */
			case_name: string;
			/** Brief */
			brief: string;
			/** Simulation Duration */
			simulation_duration?: number | null;
		};
		/** RunStateResponse */
		RunStateResponse: {
			/** Run Id */
			run_id: string;
			case: components["schemas"]["RunCaseSummary"];
			/** Contacts */
			contacts: components["schemas"]["ContactOut"][];
			/** Active Persona Id */
			active_persona_id: string;
			/** Shared Files */
			shared_files: components["schemas"]["SharedFileOut"][];
			/** Histories */
			histories: {
				[key: string]: components["schemas"]["ChatMessage"][];
			};
			/** Notes */
			notes: string;
		};
		/** SendMessagePayload */
		SendMessagePayload: {
			/** Persona Id */
			persona_id: string;
			/** Message */
			message: string;
		};
		/** SharedFileOut */
		SharedFileOut: {
			/** File Id */
			file_id: string;
			/** File Name */
			file_name: string;
			/** Content Type */
			content_type?: string | null;
			/** Url */
			url: string;
		};
		/** StartSimulationPayload */
		StartSimulationPayload: {
			/** Access Code */
			access_code: string;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
		/** TurnMeta */
		TurnMeta: {
			/** New Contacts */
			new_contacts?: components["schemas"]["ContactOut"][];
			/** Shared Files */
			shared_files?: components["schemas"]["SharedFileOut"][];
			/** Chat Ended */
			chat_ended: boolean;
			/** Chat End Reason */
			chat_end_reason: string | null;
			/** Warning Count */
			warning_count: number;
		};
		/** DeltaFrame */
		DeltaFrame: {
			/** Text */
			text: string;
		};
		/** DoneFrame */
		DoneFrame: {
			/** Reply */
			reply: string;
			/** History */
			history: components["schemas"]["ChatMessage"][];
		};
		/** ErrorFrame */
		ErrorFrame: {
			/** Detail */
			detail: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	login_api_admin_login_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LoginResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	logout_api_admin_logout_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					};
				};
			};
		};
	};
	me_api_admin_me_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LoginResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	listAdmins_api_admin_admins_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminOut"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	addAdmin_api_admin_admins_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AddAdminRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminOut"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	deleteAdmin_api_admin_admins__admin_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				admin_id: number;
			};
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminDeletedResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	presignUpload_api_uploads_presign_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PresignUploadRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PresignUploadResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	listCases_api_cases_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CaseListResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	createCase_api_cases_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CasePayload"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CaseCreatedResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	getDemoCase_api_cases_demo_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CaseDetailResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	getCase_api_cases__case_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				case_id: number;
			};
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CaseDetailResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	updateCase_api_cases__case_id__put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				case_id: number;
			};
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CaseUpdatePayload"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CaseCreatedResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	deleteCase_api_cases__case_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				case_id: number;
			};
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CaseDeletedResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	getCaseVersion_api_cases__case_id__version_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				case_id: number;
			};
			cookie?: {
				admin_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CaseVersionResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	startSimulation_api_simulations_start_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["StartSimulationPayload"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RunStateResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	getSimulationState_api_simulations__run_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RunStateResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	exportSimulation_api_simulations__run_id__export_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExportResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	updateNotes_api_simulations__run_id__notes_put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["NotesPayload"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["NotesResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	sendMessage_api_simulations__run_id__message_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SendMessagePayload"];
			};
		};
		responses: {
			/** @description Server-Sent Events stream of turn frames (event: meta|delta|done|error). */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/event-stream":
						| components["schemas"]["TurnMeta"]
						| components["schemas"]["DeltaFrame"]
						| components["schemas"]["DoneFrame"]
						| components["schemas"]["ErrorFrame"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
}
