/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_admin_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listadmins */
        get: operations["listAdmins_api_admin_admins_get"];
        put?: never;
        /** Addadmin */
        post: operations["addAdmin_api_admin_admins_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/admins/{admin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deleteadmin */
        delete: operations["deleteAdmin_api_admin_admins__admin_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presign Upload */
        post: operations["presign_upload_api_uploads_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listcases */
        get: operations["listCases_api_cases_get"];
        put?: never;
        /** Createcase */
        post: operations["createCase_api_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Getcase */
        get: operations["getCase_api_cases__case_id__get"];
        /** Updatecase */
        put: operations["updateCase_api_cases__case_id__put"];
        post?: never;
        /** Deletecase */
        delete: operations["deleteCase_api_cases__case_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulations/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Startsimulation */
        post: operations["startSimulation_api_simulations_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulations/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Getsimulationstate */
        get: operations["getSimulationState_api_simulations__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulations/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exportsimulation */
        get: operations["exportSimulation_api_simulations__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulations/{run_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Updatenotes */
        put: operations["updateNotes_api_simulations__run_id__notes_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulations/{run_id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sendmessage */
        post: operations["sendMessage_api_simulations__run_id__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}


export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddAdminRequest */
        AddAdminRequest: {
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            role: components["schemas"]["AdminRole"];
        };
        /** AdminOut */
        AdminOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            role: components["schemas"]["AdminRole"];
        };
        /**
         * AdminRole
         * @enum {integer}
         */
        AdminRole: 1 | 2;
        /** CaseCreatedResponse */
        CaseCreatedResponse: {
            /** Case Id */
            case_id: number;
        };
        /** CaseDeletedResponse */
        CaseDeletedResponse: {
            /** Ok */
            ok: boolean;
        };
        /** CaseDetail */
        CaseDetail: {
            /** Id */
            id: number;
            /** Case Name */
            case_name: string;
            /** Access Code */
            access_code?: string | null;
            /** Initial Brief */
            initial_brief: string;
            /** Common Information */
            common_information?: string | null;
            /** Simulation Duration */
            simulation_duration?: number | null;
            /** Total Non Referred Personas */
            total_non_referred_personas: number;
            /** Personas */
            personas?: components["schemas"]["PersonaOut"][];
        };
        /** CaseDetailResponse */
        CaseDetailResponse: {
            case: components["schemas"]["CaseDetail"];
        };
        /** CaseListResponse */
        CaseListResponse: {
            /** Cases */
            cases: components["schemas"]["CaseSummary"][];
        };
        /** CasePayload */
        CasePayload: {
            /** Case Name */
            case_name: string;
            /** Initial Brief */
            initial_brief: string;
            /** Common Information */
            common_information?: string | null;
            /** Simulation Duration */
            simulation_duration?: number | null;
            /** Access Code */
            access_code?: string | null;
            /** Total Non Referred Personas */
            total_non_referred_personas: number;
            /** Personas */
            personas?: components["schemas"]["PersonaPayload"][];
        };
        /** CaseSummary */
        CaseSummary: {
            /** Id */
            id: number;
            /** Case Name */
            case_name: string;
            /** Access Code */
            access_code?: string | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ContactOut */
        ContactOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            profile_photo?: components["schemas"]["PersonaPhotoOut"] | null;
            /** Availability Duration */
            availability_duration?: number | null;
            /** Known Facts */
            known_facts?: string | null;
            /** Personality Traits */
            personality_traits?: string | null;
            /** Is Referred */
            is_referred: boolean;
            /** Available */
            available: boolean;
            /** Available In */
            available_in?: number | null;
            /** Expires In */
            expires_in?: number | null;
            /** Chat Ended */
            chat_ended: boolean;
            /** Chat End Reason */
            chat_end_reason?: string | null;
            /** Warning Count */
            warning_count: number;
        };
        /** ExportCaseSummary */
        ExportCaseSummary: {
            /** Id */
            id: number;
            /** Case Name */
            case_name: string;
        };
        /** ExportPersonaOut */
        ExportPersonaOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** ExportResponse */
        ExportResponse: {
            case: components["schemas"]["ExportCaseSummary"];
            /** Personas */
            personas?: components["schemas"]["ExportPersonaOut"][];
        };
        /** FileEntry */
        FileEntry: {
            file?: components["schemas"]["FileRef"] | null;
            /** Share Conditions */
            share_conditions?: string | null;
            /** Perceived Contents */
            perceived_contents?: string | null;
        };
        /** FileRef */
        FileRef: {
            /** Object Key */
            object_key: string;
            /** File Name */
            file_name: string;
            /** Content Type */
            content_type?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Google Auth Code */
            google_auth_code: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Admin Id */
            admin_id: number;
            role: components["schemas"]["AdminRole"];
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
        };
        /** NotesPayload */
        NotesPayload: {
            /** Notes */
            notes: string;
        };
        /** NotesResponse */
        NotesResponse: {
            /** Notes */
            notes: string;
        };
        /** PersonaOut */
        PersonaOut: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            profile_photo?: components["schemas"]["FileRef"] | null;
            /** Known Facts */
            known_facts?: string | null;
            /** Personality Traits */
            personality_traits?: string | null;
            /** Availability Minutes */
            availability_minutes?: number | null;
            /** File Count */
            file_count: number;
            /** Files */
            files?: components["schemas"]["FileEntry"][];
            /** Referral Out Count */
            referral_out_count: number;
            /** Referrals */
            referrals?: components["schemas"]["ReferralOut"][];
        };
        /** PersonaPayload */
        PersonaPayload: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Role
             * @default
             */
            role: string;
            profile_photo?: components["schemas"]["FileRef"] | null;
            /** Known Facts */
            known_facts?: string | null;
            /** Personality Traits */
            personality_traits?: string | null;
            /** Availability Minutes */
            availability_minutes?: number | null;
            /** Files */
            files?: components["schemas"]["FileEntry"][];
            /** Referrals */
            referrals?: components["schemas"]["ReferralPayload"][];
        };
        /** PersonaPhotoOut */
        PersonaPhotoOut: {
            /** File Id */
            file_id?: string | null;
            /** Object Key */
            object_key: string;
            /** File Name */
            file_name: string;
            /** Content Type */
            content_type?: string | null;
            /** Url */
            url: string;
        };
        /** PresignUploadRequest */
        PresignUploadRequest: {
            /** File Name */
            file_name: string;
            /** Content Type */
            content_type?: string | null;
            /** Prefix */
            prefix?: string | null;
        };
        /** PresignUploadResponse */
        PresignUploadResponse: {
            /** Upload Url */
            upload_url: string;
            /** Object Key */
            object_key: string;
            /** File Name */
            file_name: string;
            /** Content Type */
            content_type?: string | null;
            /** Expires In */
            expires_in: number;
        };
        /** ReferralOut */
        ReferralOut: {
            /** Name */
            name: string;
            /** Conditions */
            conditions?: string | null;
            persona: components["schemas"]["PersonaOut"];
        };
        /** ReferralPayload */
        ReferralPayload: {
            /** Conditions */
            conditions?: string | null;
            persona: components["schemas"]["PersonaPayload"];
        };
        /** RunCaseSummary */
        RunCaseSummary: {
            /** Id */
            id: number;
            /** Case Name */
            case_name: string;
            /** Initial Brief */
            initial_brief: string;
            /** Simulation Duration */
            simulation_duration?: number | null;
        };
        /** RunStateResponse */
        RunStateResponse: {
            /** Run Id */
            run_id: string;
            case: components["schemas"]["RunCaseSummary"];
            /** Contacts */
            contacts: components["schemas"]["ContactOut"][];
            /** Active Persona Id */
            active_persona_id: string;
            /** Shared Files */
            shared_files: components["schemas"]["SharedFileOut"][];
            /** Histories */
            histories: {
                [key: string]: components["schemas"]["ChatMessage"][];
            };
            /** Notes */
            notes: string;
        };
        /** SendMessagePayload */
        SendMessagePayload: {
            /** Persona Id */
            persona_id: string;
            /** Message */
            message: string;
        };
        /** SharedFileOut */
        SharedFileOut: {
            /** File Id */
            file_id: string;
            /** File Name */
            file_name: string;
            /** Content Type */
            content_type?: string | null;
            /** Url */
            url: string;
        };
        /** StartSimulationPayload */
        StartSimulationPayload: {
            /** Access Code */
            access_code: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}


export type $defs = Record<string, never>;
export interface operations {
    login_api_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_admin_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listAdmins_api_admin_admins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    addAdmin_api_admin_admins_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAdminRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteAdmin_api_admin_admins__admin_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                admin_id: number;
            };
            cookie?: {
                admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_upload_api_uploads_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listCases_api_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createCase_api_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CasePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCase_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: {
                admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateCase_api_cases__case_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: {
                admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CasePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteCase_api_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: {
                admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDeletedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startSimulation_api_simulations_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSimulationPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSimulationState_api_simulations__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportSimulation_api_simulations__run_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateNotes_api_simulations__run_id__notes_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sendMessage_api_simulations__run_id__message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessagePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
