from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '073f33fc20e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # citext (case-insensitive text) backs cases.access_code below — hand-added,
    # autogenerate doesn't emit CREATE EXTENSION statements.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.CheckConstraint('role in (1, 2)', name='ck_admins_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key', name='uq_files_object_key')
    )
    op.create_table('rate_limits',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('simulations',
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_simulations_expires_at'), 'simulations', ['expires_at'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brief', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('common_information', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('root_personas', sa.Integer(), nullable=False),
    sa.Column('access_code', postgresql.CITEXT(), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=False),
    sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['admin'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_admin'), 'cases', ['admin'], unique=False)
    # ### end Alembic commands ###

    # citext is case-insensitive on equality/comparison by itself, so this partial
    # unique index (no upper() needed) enforces "one case per access code"
    # case-insensitively.
    op.execute(
        "CREATE UNIQUE INDEX idx_cases_access_code_unique ON cases (access_code) "
        "WHERE access_code IS NOT NULL AND access_code != ''"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS idx_cases_access_code_unique")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_admin'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_simulations_expires_at'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_table('rate_limits')
    op.drop_table('files')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
