"""add collaborators table and cases.version

Revision ID: 83a3b6111f69
Revises: 073f33fc20e2
Create Date: 2026-07-23 22:00:22.985303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a3b6111f69'
down_revision: Union[str, Sequence[str], None] = '073f33fc20e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborators',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'admin_id')
    )
    op.create_index(op.f('ix_collaborators_admin_id'), 'collaborators', ['admin_id'], unique=False)
    op.add_column('cases', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # NOTE: autogenerate also proposed dropping idx_cases_access_code_unique here —
    # that's a false positive. It's a hand-added partial unique index (see the
    # baseline migration, 073f33fc20e2) that isn't represented in SQLModel
    # metadata, so autogenerate always sees it as "extra" and wants to remove it.
    # Deliberately not touching it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'version')
    op.drop_index(op.f('ix_collaborators_admin_id'), table_name='collaborators')
    op.drop_table('collaborators')
    # ### end Alembic commands ###
